#!/usr/bin/env python3
from sys import argv, exit
from os import path, walk
from pathlib import Path
from getopt import getopt

# check if eyeD3 is installed.
try:
    import eyed3
except ModuleNotFoundError:
    exit(
        "eyD3 is not found! this script uses eyeD3 to edit the tags, please install it first\n $ pip install eyeD3"
    )


def main():
    # TODO: add more options?
    # TODO: Be able to only edit one file's tag.
    # FEATURE_TO_ADD: be able to change the filename element format.

    try:
        opts, args = getopt(argv[1:], "t:", ["target=", "help"])

    except:
        exit(f"unrecognised option, please see --help to see avaliable options..")

    target_dir = None

    for opt, arg in opts:
        if opt in ["-t", "--target"]:
            target_dir = arg

        elif opt == "--help":
            exit(
                    "(Re)tags audio files in a specified directory\n\nusage:\n    auto-tag [option] [directory]    edit tags of the files in the directory\n\nOptions:\n    -t, --target     specify a target directory\n    --help           display this help information and exit"
            )

    try:
        if not None and path.isdir(target_dir):
            file_tagger(target_dir)

    except TypeError:
        if path.isdir(argv[1]):
            target_dir = argv[1]
            file_tagger(target_dir)

        else:
            exit("an error occured, please enter the correct target directory")

    except:
        exit("an error occured, please enter the correct target directory")


def file_tagger(target_dir):

    # list of formats the program will look for in the directory.
    audio_formats = [".mp3", ".wav", ".aac", ".m4a", ".flac", ".ogg", ".opus"]

    audio_file_list = []

    # list audio files in the target directory
    for dirpath, dirnames, files in walk(target_dir):
        for file_name in files:
            for i in audio_formats:
                if file_name.lower().endswith(i):
                    audio_file_list.append(path.join(dirpath, file_name))

    count = 0

    # Iterate through the list of audio files, and write they're tags.
    for file in audio_file_list:
        file_name = path.basename(file)

        # remove the file extention from the list
        tag_element = file_name.split(Path(file).suffix)

        # get elements from the lists
        tag_element = tag_element[-2].split(" - ")

        # shows how many files have been re-tagged.
        total_file_count = len(audio_file_list)
        if total_file_count > 1:
            count+=1
            progress = f"{total_file_count}/{count} => {round((count * 100) / total_file_count)}%"
        else:
            progress = ""

        try:
            audiofile = eyed3.load(file)

            audiofile.tag.artist = tag_element[0]
            audiofile.tag.album = tag_element[1]
            audiofile.tag.title = tag_element[2]
            audiofile.tag.save()

            print(f"Edited {file_name} tag. {progress}")

        except IndexError:
            exit(
                f'An error occured when editing {file_name} tag.\nMake sure the files are named with the correct format.. "Artist - Album - Title"'
            )

        except:
            exit(f"An error occured when editing {file_name} tag.")


if __name__ == "__main__":
    main()
