#!/bin/bash
prog="
Librewolf
Firefox
TorBrowser
FreeTube
"

cmd=$(dmenu -i -p 'Choose a Program' <<< "$prog")

cd "$IMG_PATH" || exit
case ${cmd%% *} in

	Firefox)firefox & ;;
	Librewolf)librewolf &	;;
	TorBrowser)torbrowser-launcher & ;;
	FreeTube)freetube-bin & ;;

  	*)		exec "'${cmd}'"  ;;
esac

