#!/bin/bash

[ ! "$(command -V "fzf")" ] || \
    [ ! "$(command -V "dmenu")" ] && exit 1

[ -d "$1" ] && start_dir="$1" || exit 1

prompt="dmenu -i -l 50"
[ "$2" = "-t" ] && prompt="fzf"

timeout=10
count=0

query=""

path="$start_dir"
prev_path=""

while(true); do
    # [ "$count" -eq "$timeout" ] && exit 1

    query="$(find -L "$path" -maxdepth 1 -mindepth 1 \
        -exec basename {} \; | $prompt )"
    [ -z "$query" ] && [ "$path" == "$start_dir" ] && break


    if [ -n "$query" ]; then
        if [ -f "$path/$query" ]; then
            printf "%s\n" "$path/$query" 2>/dev/null &
            break

        elif [ -d "$path/$query" ]; then
            path="$path/$query"
            continue
        fi
    else
        path="$start_dir"
    fi
    # count=$(( count + 1 ))
done
