#!/usr/bin/env bash

[ ! "$(command -V "fzf")" ] || \
    [ ! "$(command -V "dmenu")" ] && exit 1

prompt="dmenu -i -l 50"
[ "$2" = "-t" ] && prompt="fzf"

option="$(printf "%s\n" \
    "1. Networking" "2. Screenshot" "3. Password"\
    "4. Books" "5. Videos" "6. Toggle Touchpad" \
    "7. Bookmarks" \
    "8. Display arandr" \
    "9. Display dm-xrandr" \
    | $prompt | tr " " _)"

case ${option} in
    1._Networking)          networkmanager_dmenu    || exit 1 ;;
    2._Screenshot)          dm-screenshot           || exit 1 ;;
    3._Password)            passmenu                || exit 1 ;;
    4._Books)               fbook                   || exit 1 ;;
    5._Videos)              fvideo                  || exit 1 ;;
    6._Toggle_Touchpad)     toggle_touchpad         || exit 1 ;;
    7._Bookmarks)           dm-bookmarks            || exit 1 ;;
    8._Display_arandr)      arandr                  || exit 1 ;;
    9._Display_dm-xrandr)   dm-xrandr               || exit 1 ;;
    *) exit 0;;
esac
