#!/bin/sh

library_dir="$HOME/Documents/Books"
dm_cmd="dmenu -l 10 -p"
pdf_reader="zathura"

cmd=$( $dm_cmd "Choose a Category! " <<< $(ls $library_dir))

if [[ "$cmd" == "Coding" ]]; then
  content_0=$( $dm_cmd "Choose a Category! " <<< $( ls "$library_dir/$cmd" ))
  if [ "$content_0" ]; then
    content_1=$( $dm_cmd "Choose a Book! " <<< $( ls "$library_dir/$cmd/$content_0" ))
    if [ "$content_1" ]; then
      $pdf_reader "$library_dir/$cmd/$content_0/$content_1" &
      exit 0
    fi
  fi

elif [ "$cmd" ]; then
  content_0=$( $dm_cmd "Choose a Book! " <<< $(ls "$library_dir/$cmd"))
  if [ "$content_0" ]; then
    $pdf_reader "$library_dir/$cmd/$content_0" &
    exit 0
  fi
fi
