#!/bin/bash

set -o pipefail

[ ! "$(command -V "maim")" ] || \
    [ ! "$(command -V "fzf")" ] || \
    [ ! "$(command -V "dmenu")" ] \
    && exit 1

notify()
{
    notify-send "dm-screenshot" "Screenshot Taken!"
}

prompt="dmenu -c -i -bw 1 -l 50"
[ "$2" = "-t" ] && prompt="fzf"

save_path="$HOME/Pictures/Screenshots"

[ ! -d "$save_path" ] && mkdir -p "$save_path"

file_name="screenshot-$(date '+%d-%m-%y@%s').png"

maim_cmd="maim -B -u -f png -m 5 --quiet"

prompt="$(printf "%s\n" \
    "1. ClipSection" \
    "2. ClipScreen" \
    "3. Take Shot" \
    "4. Section" \
    "5. View Screenshots" \
    "6. FlameShot" | \
    $prompt | tr " " _)"

case ${prompt} in
    1._ClipSection) $maim_cmd -s | xclip -selection clipboard -t image/png && notify ||  exit 1 ;;
    2._ClipScreen) $maim_cmd -d 0.2 | xclip -selection clipboard -t image/png && notify ||  exit 1 ;;
    3._Take_Shot) $maim_cmd -d 0.2 "$save_path/$file_name" && notify || exit 1 ;;
    4._Section) $maim_cmd -s "$save_path/$file_name" && notify || exit 1 ;;
    5._View_Screenshots) sxiv "$save_path" && notify || exit 1 ;;
    6._FlameShot) flameshot gui || exit 1 ;;
    *) exit 1;;
esac

exit 0
