#!/usr/bin/env bash

script_dir="$HOME/.local/bin/scripts/"

sel_script=$(find "$script_dir" \( ! -iname "dm-scripts" -iname "dm-*" \) | \
    dmenu -p "Choose a Script: " -l 5 -i)

if [ "$sel_script" ]; then
    bash -e "$sel_script"
fi
