#!/bin/bash

# Videos/
# \---- category/
#       \---- video.mp4

VIDEO_DIR="$HOME/Videos"
PLAYER="mpv"

[ ! "$(command -V "$PLAYER")" ] && exit 1

if [ -d "$VIDEO_DIR" ]; then
	sel_category="$(find "$VIDEO_DIR" -maxdepth 1 -mindepth 1 \
        -type d  \( -not -path '*/\.*' \) -exec basename {} \; | \
        dmenu -i -l 10 -p "Category: " )"
    if [ "$sel_category" ]; then
        sel_video="$(find "$VIDEO_DIR/$sel_category" -type f | \
            dmenu -i -l 50 -p "Video: ")"
        if [ "$sel_video" ]; then
            if [ -f "$sel_video" ]; then
                "$PLAYER" "$sel_video" &
            fi
        fi
    fi
fi

exit 1
