#!/bin/sh

book_dir="$HOME/Documents/Books"
[ ! -d "$book_dir" ] && exit 1

[ "$(command -V "notify-send")" ] && notify=1

[ -n "$READER" ] && \
    reader="$READER" || reader="xdg-open"

[ ! "$(command -V "$reader")" ] || \
    [ ! "$(command -V "dm-dir")" ] && exit 1

dm_dir_cmd="dm-dir -d "$book_dir" -s $1"
sel_book="$($dm_dir_cmd)"

[ "$?" -eq 1 ] || [ -z "$sel_book" ] && exit 1

[ "$notify" ] && notify-send "fbook" "Opening, $(basename "$sel_book")" 2>/dev/null &

"$reader" "$sel_book" 2>/dev/null &

exit 0
