#!/bin/sh

book_dir="$HOME/Documents/Books"
[ ! -d "$book_dir" ] && exit 1

[ "$(command -V "notify-send")" ] && notify=1

[ -n "$READER" ] && \
    reader="$READER" || reader="xdg-open"

[ ! "$(command -V "$reader")" ] || \
    [ ! "$(command -V "dm-dir")" ] && exit 1

sel_book="$(dm-dir "$book_dir" "$1")"

if [ -n "$sel_book" ]; then
    [ "$notify" ] && notify-send "fbook" "Opening $(basename "$sel_book")" 2>/dev/null &
    "$reader" "$sel_book" 2>/dev/null & 
    exit 0
else
    exit 1
fi
