#!/bin/sh

vid_dir="$HOME/Videos"
[ ! -d "$vid_dir" ] && exit 1

[ "$(command -V "notify-send")" ] && notify=1

player_args=""

[ -n "$VIDEO" ] && \
    player="$VIDEO" || player="xdg-open"

[ "$player" = "mpv" ] && \
    player_args="--no-config --load-scripts=no"

[ ! "$(command -V "$player")" ] || \
    [ ! "$(command -V "dm-dir")" ] && exit 1

sel_video="$(dm-dir "$vid_dir" "$1")"

[ -z "$sel_video" ] && exit 1

[ "$notify" ] && notify-send "fvideo" "Opening, $(basename "$sel_video")" 2>/dev/null &

if ( file --mime-type "$sel_video" | grep -q "audio" ) && [ "$player" = "mpv" ]; then
    $TERMINAL "$player" "$player_args" "$sel_video" 2>/dev/null &
else
    "$player" "$player_args" "$sel_video" 2>/dev/null &
fi

exit 0
