#!/bin/sh

# Videos/
# \---- category/
#       \---- video.mp4

vid_dir="$HOME/Videos"
[ ! -d "$vid_dir" ] && exit 1

[ -n "$VIDEO" ] && \
    v_player="$VIDEO" || v_player="xdg-open"

[ ! "$(command -V "$v_player")" ] || \
    [ ! "$(command -V "fzf")" ] || \
    [ ! "$(command -V "dmenu")" ] && exit 1

prompt="dmenu -i -l 50"
[ "$1" = "-t" ] && prompt="fzf"

while(true); do

    category=""
    vid=""

    category="$(find -L "$vid_dir" \
        -maxdepth 1 \
        -mindepth 1 \
        -type d \( -not -path '*/\.*' \) \
        -exec basename {} \; | $prompt )"
    
    [ -z "$category" ] && exit 1

    if [ -z "$vid" ] && [ -n "$category" ]; then

        vid="$(find -L "$vid_dir/$category" -type f | \
            awk -F "$vid_dir/$category/" '{print $2}' | $prompt )"
    fi

    [ -f "$vid_dir/$category/$vid" ] && break

done

if [ -n "$vid" ] && [ -n "$category" ]; then
    "$v_player" "$vid_dir/$category/$vid" &
    exit 0
else
    exit 1
fi
