#!/bin/env bash

# manpage sections
# 1   Executable programs or shell commands
# 2   System calls (functions provided by the kernel)
# 3   Library calls (functions within program libraries)
# 4   Special files (usually found in /dev)
# 5   File formats and conventions, e.g. /etc/passwd
# 6   Games
# 7   Miscellaneous (including macro packages and conventions), e.g. man(7), groff(7), man-pages(7)
# 8   System administration commands (usually only for root)
# 9   Kernel routines [Non standard]

manpages=()
sections_added=()

load_pages()
{
    local section="$1"
    local man_path="/usr/share/man/man$section"

    [ ! -d "$man_path" ] && return 0
    [ "$section" -lt "1" ] && [ "$section" -gt "9" ] && return 0

    # Dont add a section twice!
    grep -q "$section" <<< "${sections_added[*]}" && return 0

    # delimiter = ".";  the files are named [man_entry].[section].gz
    while IFS="." read -r entry _ ; do
        manpages+=("$entry($1) ")
    done <<< "$(find "$man_path" -type f -printf "%f\n")"

    sections_added+=("$section")
}

while [ $# -gt 0 ]; do
    case "$1" in
        --all)
            for (( n=1; n <= 9; n++ )); do
                load_pages "$n"
            done
            break;
        ;;
        *)
            load_pages "$1"
            shift
        ;;
    esac
done

[ -z "${manpages[*]}" ] && exit 1

sel_page="$(printf "%s\n" "${manpages[@]}" | fzf $FZFTHEME --header "FZF Manpage")"

[ -z "$sel_page" ] && exit 1

man "$sel_page" && exit 0
