#! /usr/bin/env python3
import time
from os import path, makedirs, listdir
from pathlib import Path
from shutil import move

# get a date of when the file was created
def get_creation_time(format, file):
    timestamp_obj = time.strptime(time.ctime(path.getctime(file)))

    return time.strftime(format, timestamp_obj)


# get the extention from the filename by using "." as a field seperator
def get_extention(file):
    if len(file.split(".")) == 1:
        return "unknown"
    else:
        # this will split the filename to a list
        # take anything after the first period "."
        # and join it, assuming it is the extention.
        return ".".join(file.split(".")[1:])


def main():
    download_dir = f"{Path.home()}/Downloads"
    download_storage = f"{download_dir}/storage"

    if not path.isdir(download_dir):
        exit("Download directory not found, exiting...")

    # make a list of files in the download directory
    file_list = listdir(download_dir)

    for file in file_list:
        org_path = f"{download_dir}/{file}"
        extention = get_extention(org_path)
        creation_date = get_creation_time("%d-%m-%Y", org_path)
        nw_path = f"{download_storage}/{creation_date}/{extention}"

        if path.isfile(org_path):

            # make the directories
            if not path.isdir(nw_path):
                makedirs(nw_path)

            # move the files to the directory
            move(org_path, f"{nw_path}/{file}")
            print(f"- moved {org_path} to {nw_path}/{file}")


if __name__ == "__main__":
    main()
