#!/bin/bash

prog="
1.poweroff
2.reboot
3.tty
4.lockscreen
"

cmd=$(dmenu -i -p 'Choose a Power Option: ' <<< "$prog")

cd $IMG_PATH
case ${cmd%% *} in

	1.poweroff) poweroff ;;
	2.reboot)	reboot ;;
	3.tty) pkill -15 Xorg ;;
	4.lockscreen)	xsecurelock ;;

  	*)		exec "'${cmd}'"  ;;
esac
