#!/bin/bash

PROJECT_DIR=(
    "$HOME/Programming/repositories"
    "$HOME/Programming/work_in_progress"
)

# creates a window
new_window()
{
    session_name="$1"
    window_name="$2"
    cmd="$3"

    tmux new-window -t "$session_name" 
    tmux rename-window -t "$session_name" "$window_name"
    tmux send-keys -t "$session_name" "$cmd" C-m
}

# setups the window layouts
create_workspace()
{
    session_name="$1"
    sel_window="1"

    tmux rename-window -t "$session_name" "ED"
    tmux send-keys -t "$session_name" "nvim" C-m

    # new_window "$session_name" "FM" "ranger"

    tmux new-window -t "$session_name"
    tmux rename-window -t "$session_name" "TERM"

    tmux select-window -t "$session_name:$sel_window"
}

tmux_start()
{
    session_name="MAIN"

    if ! tmux has-session -t="$session_name" 2> /dev/null; then
        sel_window="1"

        tmux new-session -ds "$session_name" -c "$HOME"

        tmux rename-window -t "$session_name" "TASK"
        tmux send-keys -t "$session_name" "calcurse" C-m

        new_window "$session_name" "FILE" "ranger"
        new_window "$session_name" "MUSIC" "cmus"

        tmux select-window -t "$session_name:$sel_window"
    fi

    tmux switch-client -t "$selected_name" \
        || tmux attach-session -t "$selected_name"

    exit 0
}

case "$1" in
    -start) tmux_start ;;

    # sessionize a specified directory
	-t) [ ! -d "$2" ] && exit 1
        selected="$2"
    ;;

    # sessionize the current working directory
	-cwd) selected="$(find -L "$(pwd)" \
		-mindepth 1 -maxdepth 2 -type d | fzf)";;

    # sessionize a directory from the PROJECT_DIR
    *) selected="$(find -L "${PROJECT_DIR[@]}" \
        -mindepth 1 -maxdepth 1 -type d | fzf)";;
esac

[ -z "$selected" ] || [ ! -d "$selected" ] && exit 1

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [ -z "$TMUX" ] && [ -z "$tmux_running" ]; then
    tmux new-session -s "$selected_name" -c "$selected"
    exit 0
fi

if ! tmux has-session -t="$selected_name" 2> /dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected"
    create_workspace "$selected_name"
fi

tmux switch-client -t "$selected_name" \
	|| tmux attach-session -t "$selected_name"
