#!/bin/bash

PROJECT_DIR=( 
	"$HOME/Programming/repositories" 
	"$HOME/.dotfile" 
	"$HOME/Programming/work_in_progress" 
)

create_windows(){
    session_name="$1"
    sel_window="1"

    tmux rename-window -t "$session_name" "ED"
    tmux send-keys -t "$session_name" "nvim" C-m

    tmux new-window -t "$session_name"
    tmux rename-window -t "$session_name" "TERM"

    # tmux new-window -t "$session_name"
    # tmux rename-window -t "$session_name" "FM"
    # tmux send-keys -t "$session_name" "ranger" C-m

    tmux select-window -t "$session_name:$sel_window"
}

case "$1" in
	-t) selected="$2";;
	-cd) selected="$(find "$(pwd)" \
		-mindepth 1 -maxdepth 2 -type d | fzf)";;
	*) selected="$(find "${PROJECT_DIR[@]}" \
		-mindepth 1 -maxdepth 1 -type d | fzf)";;
esac

[ -z "$selected" ] || [ ! -d "$selected" ] && exit 1

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [ -z "$TMUX" ] && [ -z "$tmux_running" ]; then
    tmux new-session -s "$selected_name" -c "$selected"
    exit 0
fi

if ! tmux has-session -t="$selected_name" 2> /dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected"
    create_windows "$selected_name"
fi

tmux switch-client -t "$selected_name" \
	|| tmux attach-session -t "$selected_name"
