#!/bin/env bash

touchpad_status="$(xinput list-props "SynPS/2 Synaptics TouchPad" | \
    awk -F ":" '/Device Enabled/ {print $2}' | tr -d '\t')"

if [ "$touchpad_status" == "1" ]; then
    [ $(command -v "notify-send") ] && notify-send "Toggling OFF touchpad"
    xinput --set-prop "SynPS/2 Synaptics TouchPad" "Device Enabled" 0
else
    [ $(command -v "notify-send") ] && notify-send "Toggling ON touchpad"
    xinput --set-prop "SynPS/2 Synaptics TouchPad" "Device Enabled" 1
fi
